/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#ff7162",
        "surface-variant": "#22262b",
        "surface-tint": "#85adff",
        "primary-dim": "#0070eb",
        "error-container": "#9f0519",
        "secondary-fixed-dim": "#4af03b",
        "tertiary-container": "#f9362c",
        "on-background": "#f8f9fe",
        "background": "#0b0e11",
        "primary-fixed": "#6c9fff",
        "on-secondary-container": "#e7ffda",
        "primary-container": "#6c9fff",
        "surface-container-high": "#1c2024",
        "inverse-primary": "#005bc2",
        "on-secondary": "#005e00",
        "on-primary-container": "#00214f",
        "surface-container-low": "#101417",
        "on-error-container": "#ffa8a3",
        "outline-variant": "#45484c",
        "surface-bright": "#282d31",
        "tertiary-fixed": "#ff9385",
        "secondary": "#5bff49",
        "error-dim": "#d7383b",
        "tertiary-dim": "#e2241f",
        "on-tertiary": "#4a0001",
        "on-error": "#490006",
        "surface-container-highest": "#22262b",
        "on-secondary-fixed": "#004900",
        "on-tertiary-fixed": "#3a0001",
        "on-tertiary-container": "#000000",
        "error": "#ff716c",
        "on-primary": "#002c65",
        "outline": "#737679",
        "inverse-surface": "#f8f9fe",
        "surface-dim": "#0b0e11",
        "primary": "#85adff",
        "on-primary-fixed": "#000000",
        "tertiary-fixed-dim": "#ff7c6c",
        "on-surface-variant": "#a9abaf",
        "surface": "#0b0e11",
        "surface-container": "#161a1e",
        "inverse-on-surface": "#535559",
        "secondary-container": "#006e01",
        "on-surface": "#f8f9fe",
        "on-secondary-fixed-variant": "#006901",
        "primary-fixed-dim": "#5191ff",
        "on-primary-fixed-variant": "#002a61",
        "secondary-fixed": "#5bff49",
        "secondary-dim": "#4af03b",
        "on-tertiary-fixed-variant": "#7a0004",
        "surface-container-lowest": "#000000"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
